#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Скрипт для получения WSDC Points из реестра по списку имён из Google Sheets.

Использование:
    python wsdc_from_google_sheet.py 2026-01-28

Автор: Generated by AI
"""

import sys
import time
import re
import pandas as pd
import requests
from bs4 import BeautifulSoup
from typing import Optional, List, Dict, Any
from urllib.parse import quote


# ==============================================================================
# НАСТРОЙКИ
# ==============================================================================

# URL Google Sheets (публичная ссылка)
GOOGLE_SHEET_ID = "1ZaJXXCGQl8a1nrn1Bq6Wf2HjMI3dUGVLdb5vHT0P3LE"

# URL WSDC Points Registry
WSDC_SEARCH_API = "https://points.worldsdc.com/api/dancer"
WSDC_LOOKUP_URL = "https://points.worldsdc.com/lookup2020"

# Пауза между запросами к WSDC (в секундах)
# Увеличьте, если получаете много 404 ошибок (rate limiting)
REQUEST_DELAY_MIN = 1.5
REQUEST_DELAY_MAX = 3.0

# Заголовки для запросов (имитация браузера)
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
}


# ==============================================================================
# ТРАНСЛИТЕРАЦИЯ РУССКИХ ИМЁН В АНГЛИЙСКИЕ (СТИЛЬ WSDC)
# ==============================================================================

# Таблица транслитерации (WSDC-стиль, похожий на загранпаспорт РФ)
TRANSLIT_TABLE = {
    # Заглавные
    'А': 'A', 'Б': 'B', 'В': 'V', 'Г': 'G', 'Д': 'D', 'Е': 'E', 'Ё': 'E',
    'Ж': 'Zh', 'З': 'Z', 'И': 'I', 'Й': 'Y', 'К': 'K', 'Л': 'L', 'М': 'M',
    'Н': 'N', 'О': 'O', 'П': 'P', 'Р': 'R', 'С': 'S', 'Т': 'T', 'У': 'U',
    'Ф': 'F', 'Х': 'Kh', 'Ц': 'Ts', 'Ч': 'Ch', 'Ш': 'Sh', 'Щ': 'Shch',
    'Ъ': '', 'Ы': 'Y', 'Ь': '', 'Э': 'E', 'Ю': 'Yu', 'Я': 'Ya',
    # Строчные
    'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'e',
    'ж': 'zh', 'з': 'z', 'и': 'i', 'й': 'y', 'к': 'k', 'л': 'l', 'м': 'm',
    'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u',
    'ф': 'f', 'х': 'kh', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'shch',
    'ъ': '', 'ы': 'y', 'ь': '', 'э': 'e', 'ю': 'yu', 'я': 'ya',
}

# Исключения для имён (русское -> английское)
# Добавляйте сюда имена, которые транслитерируются нестандартно
NAME_EXCEPTIONS = {
    # Примеры популярных имён с нестандартной транслитерацией на WSDC:
    'Алексей': 'Alexey',
    'Александр': 'Alexander',
    'Александра': 'Alexandra',
    'Анастасия': 'Anastasia',
    'Дмитрий': 'Dmitry',
    'Евгений': 'Evgeny',
    'Евгения': 'Evgenia',
    'Екатерина': 'Ekaterina',
    'Максим': 'Maxim',
    'Михаил': 'Mikhail',
    'Наталья': 'Natalia',
    'Наталия': 'Natalia',
    'Николай': 'Nikolay',
    'Сергей': 'Sergey',
    'Татьяна': 'Tatiana',
    'Юлия': 'Yulia',
    'Юрий': 'Yuri',
    'Ксения': 'Ksenia',
    'Оксана': 'Oksana',
    'Ольга': 'Olga',
    'Виктория': 'Victoria',
    'Виктор': 'Victor',
    'Владимир': 'Vladimir',
    'Владислав': 'Vladislav',
    'Андрей': 'Andrey',
    'Антон': 'Anton',
    'Артём': 'Artem',
    'Артем': 'Artem',
    'Борис': 'Boris',
    'Валерий': 'Valery',
    'Валерия': 'Valeria',
    'Вадим': 'Vadim',
    'Василий': 'Vasily',
    'Георгий': 'Georgy',
    'Григорий': 'Grigory',
    'Даниил': 'Daniil',
    'Денис': 'Denis',
    'Иван': 'Ivan',
    'Игорь': 'Igor',
    'Илья': 'Ilya',
    'Кирилл': 'Kirill',
    'Константин': 'Konstantin',
    'Леонид': 'Leonid',
    'Мария': 'Maria',
    'Марина': 'Marina',
    'Никита': 'Nikita',
    'Олег': 'Oleg',
    'Павел': 'Pavel',
    'Пётр': 'Petr',
    'Петр': 'Petr',
    'Роман': 'Roman',
    'Светлана': 'Svetlana',
    'Станислав': 'Stanislav',
    'Степан': 'Stepan',
    'Тимофей': 'Timofey',
    'Фёдор': 'Fedor',
    'Федор': 'Fedor',
    'Эдуард': 'Eduard',
    'Яна': 'Yana',
    'Ярослав': 'Yaroslav',
    # Добавьте ваши исключения здесь:
    # 'ИмяНаРусском': 'NameInEnglish',
}

# Исключения для полных ФИО (если нужно переопределить всё имя целиком)
FULL_NAME_EXCEPTIONS = {
    # 'Иванов Иван Иванович': 'Ivan Ivanov',
}


def ru_to_en(name_ru: str) -> str:
    """
    Транслитерация русского имени в английское (WSDC-стиль).
    
    Args:
        name_ru: Имя на русском (формат: "Фамилия Имя" или "Фамилия Имя Отчество")
    
    Returns:
        Имя на английском в формате "Имя Фамилия"
    
    Примеры:
        >>> ru_to_en("Кочев Алексей")
        'Alexey Kochev'
        >>> ru_to_en("Иванова Татьяна")
        'Tatiana Ivanova'
        >>> ru_to_en("Захаров Дмитрий")
        'Dmitry Zakharov'
    """
    if not name_ru:
        return ""
    
    name_ru = name_ru.strip()
    
    # Проверяем полное ФИО в исключениях
    if name_ru in FULL_NAME_EXCEPTIONS:
        return FULL_NAME_EXCEPTIONS[name_ru]
    
    # Разбиваем на части (фамилия, имя, отчество)
    parts = name_ru.split()
    result_parts = []
    
    for part in parts:
        # Проверяем, есть ли это слово в исключениях
        if part in NAME_EXCEPTIONS:
            result_parts.append(NAME_EXCEPTIONS[part])
        else:
            # Транслитерируем посимвольно
            transliterated = ""
            for char in part:
                if char in TRANSLIT_TABLE:
                    transliterated += TRANSLIT_TABLE[char]
                else:
                    transliterated += char  # Оставляем как есть (латиница, цифры и т.д.)
            result_parts.append(transliterated)
    
    # Формат в Google Sheet: "Фамилия Имя" или "Фамилия Имя Отчество"
    # Для WSDC нужен формат: "Имя Фамилия"
    
    if len(result_parts) == 3:
        # Формат: Фамилия Имя Отчество -> Имя Фамилия (отчество отбрасываем)
        return f"{result_parts[1]} {result_parts[0]}"
    elif len(result_parts) == 2:
        # Формат: Фамилия Имя -> Имя Фамилия
        return f"{result_parts[1]} {result_parts[0]}"
    else:
        return " ".join(result_parts)


# ==============================================================================
# РАБОТА С GOOGLE SHEETS
# ==============================================================================

def read_google_sheet(sheet_id: str, sheet_name: Optional[str] = None) -> pd.DataFrame:
    """
    Читает Google Sheet в pandas DataFrame.
    
    Args:
        sheet_id: ID Google таблицы из URL
        sheet_name: Название листа (опционально, по умолчанию первый лист)
    
    Returns:
        DataFrame с данными из таблицы
    """
    # Формируем URL для экспорта в CSV
    if sheet_name:
        url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={quote(sheet_name)}"
    else:
        url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv"
    
    print(f"Загружаю данные из Google Sheets...", flush=True)
    
    try:
        df = pd.read_csv(url)
        print(f"Загружено {len(df)} строк", flush=True)
        return df
    except Exception as e:
        # Пробуем альтернативный URL
        print(f"Первый URL не сработал: {e}", flush=True)
        url_alt = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"
        try:
            df = pd.read_csv(url_alt)
            print(f"Загружено {len(df)} строк", flush=True)
            return df
        except Exception as e2:
            raise Exception(f"Не удалось загрузить Google Sheet: {e}, {e2}")


# ==============================================================================
# РАБОТА С WSDC POINTS REGISTRY
# ==============================================================================

def search_wsdc_dancer(name_en: str, session: requests.Session) -> List[Dict[str, Any]]:
    """
    Поиск танцора в WSDC по имени.
    
    Args:
        name_en: Имя на английском
        session: requests Session
    
    Returns:
        Список найденных танцоров с их данными
    """
    params = {"q": name_en}
    
    try:
        response = session.get(WSDC_SEARCH_API, params=params, headers=HEADERS, timeout=30)
        
        # Не используем raise_for_status(), проверяем вручную
        if response.status_code == 404:
            # 404 может означать "не найдено" или rate limiting
            return []
        
        if response.status_code != 200:
            print(f"  HTTP {response.status_code} для '{name_en}'", flush=True)
            return []
        
        try:
            data = response.json()
        except Exception:
            return []
        
        if data.get("type") == "names" and "names" in data:
            # Убираем дубликаты по wsdc_id
            seen_ids = set()
            unique_names = []
            for dancer in data["names"]:
                if dancer["wsdc_id"] not in seen_ids:
                    seen_ids.add(dancer["wsdc_id"])
                    unique_names.append(dancer)
            return unique_names
        
        return []
    
    except requests.exceptions.Timeout:
        print(f"  Таймаут для '{name_en}'", flush=True)
        return []
    except requests.exceptions.ConnectionError:
        print(f"  Ошибка соединения для '{name_en}'", flush=True)
        return []
    except Exception as e:
        print(f"  Ошибка поиска '{name_en}': {e}", flush=True)
        return []


def get_dancer_points_from_html(wsdc_id: int, session: requests.Session) -> Dict[str, Any]:
    """
    Получает поинты танцора, парся HTML страницы.
    
    Примечание: WSDC использует JavaScript для рендеринга данных,
    поэтому этот метод может не работать для всех случаев.
    Используется requests_html как fallback.
    
    Args:
        wsdc_id: WSDC ID танцора
        session: requests Session
    
    Returns:
        Словарь с данными танцора
    """
    url = f"{WSDC_LOOKUP_URL}?q={wsdc_id}"
    
    try:
        response = session.get(url, headers=HEADERS, timeout=30)
        response.raise_for_status()
        
        soup = BeautifulSoup(response.text, 'html.parser')
        
        result = {
            "wsdc_id": wsdc_id,
            "name": None,
            "divisions": []
        }
        
        # CSS-селекторы для парсинга страницы WSDC
        # ВАЖНО: Если верстка изменится, нужно обновить эти селекторы
        
        # Селектор для имени танцора (h1 с именем и ID)
        # Пример: "Jordan Frisbee (311)"
        name_heading = soup.find('h1')
        if name_heading:
            name_text = name_heading.get_text(strip=True)
            # Извлекаем имя без ID в скобках
            match = re.match(r'^(.+?)\s*\(\d+\)$', name_text)
            if match:
                result["name"] = match.group(1).strip()
        
        # Селектор для секций с дивизионами
        # Ищем h2 с текстом типа "West Coast Swing - Leader"
        role_headings = soup.find_all('h2')
        
        for role_h2 in role_headings:
            role_text = role_h2.get_text(strip=True)
            # Пример: "West Coast Swing - Leader"
            if ' - ' in role_text:
                parts = role_text.split(' - ')
                if len(parts) >= 2:
                    role = parts[-1].strip()  # Leader / Follower
                    
                    # Ищем h3 с дивизионами после этого h2
                    # Пример: "Novice 24 points"
                    next_elem = role_h2.find_next_sibling()
                    while next_elem and next_elem.name != 'h2':
                        if next_elem.name == 'h3':
                            div_text = next_elem.get_text(strip=True)
                            # Парсим "Division XX points"
                            match = re.match(r'^(\w+(?:\s+\w+)?)\s+(\d+)\s*points?$', div_text, re.IGNORECASE)
                            if match:
                                division = match.group(1).strip()
                                points = int(match.group(2))
                                result["divisions"].append({
                                    "division": division,
                                    "role": role,
                                    "points": points
                                })
                        next_elem = next_elem.find_next_sibling()
        
        return result
    
    except Exception as e:
        print(f"  Ошибка получения данных для ID {wsdc_id}: {e}", flush=True)
        return {"wsdc_id": wsdc_id, "name": None, "divisions": []}


def get_dancer_points_via_api(wsdc_id: int, session: requests.Session) -> Dict[str, Any]:
    """
    Получает поинты танцора через API эндпоинт /lookup2020/find.
    
    Это более быстрый и надёжный способ, чем Playwright.
    
    Args:
        wsdc_id: WSDC ID танцора
        session: requests Session
    
    Returns:
        Словарь с данными танцора
    """
    result = {
        "wsdc_id": wsdc_id,
        "name": None,
        "divisions": []
    }
    
    try:
        # Сначала получаем CSRF токен из формы
        response = session.get(WSDC_LOOKUP_URL, headers=HEADERS, timeout=30)
        response.raise_for_status()
        
        soup = BeautifulSoup(response.text, 'html.parser')
        token_input = soup.find('input', {'name': '_token'})
        if not token_input:
            print(f"    Не найден CSRF токен", flush=True)
            return result
        
        token = token_input.get('value', '')
        if not token:
            print(f"    CSRF токен пустой", flush=True)
            return result
        
        # Делаем POST запрос к /lookup2020/find с wsdc_id
        find_url = "https://points.worldsdc.com/lookup2020/find"
        data = {
            '_token': token,
            'num': wsdc_id
        }
        
        response = session.post(find_url, data=data, headers=HEADERS, timeout=30)
        response.raise_for_status()
        
        # Ответ должен быть JSON или HTML
        try:
            json_data = response.json()
        except:
            # Если не JSON, парсим HTML
            soup = BeautifulSoup(response.text, 'html.parser')
            
            # Ищем имя в h1
            h1 = soup.find('h1')
            if h1:
                name_text = h1.get_text(strip=True)
                match = re.match(r'^(.+?)\s*\(\d+\)$', name_text)
                if match:
                    result["name"] = match.group(1).strip()
            
            # Ищем дивизионы и роли
            h2_elements = soup.find_all('h2')
            for h2 in h2_elements:
                h2_text = h2.get_text(strip=True)
                if ' - ' in h2_text and ('Leader' in h2_text or 'Follower' in h2_text):
                    parts = h2_text.split(' - ')
                    if len(parts) >= 2:
                        role = parts[-1].strip()
                        
                        # Ищем h3 после этого h2
                        next_elem = h2.find_next_sibling()
                        while next_elem and next_elem.name != 'h2':
                            if next_elem.name == 'h3':
                                div_text = next_elem.get_text(strip=True)
                                match = re.match(r'^([\w-]+(?:\s+[\w-]+)?)\s+(\d+)\s*points?$', div_text, re.IGNORECASE)
                                if match:
                                    division = match.group(1).strip()
                                    points = int(match.group(2))
                                    result["divisions"].append({
                                        "division": division,
                                        "role": role,
                                        "points": points
                                    })
                            next_elem = next_elem.find_next_sibling()
            
            return result
        
        # Обрабатываем JSON ответ
        # Структура: {"leader": {...}, "follower": {...}}
        # Каждая роль содержит: dancer, level, placements
        
        dancer_info = None
        roles_data = []
        
        # Проверяем leader
        if 'leader' in json_data:
            leader_data = json_data['leader']
            if leader_data.get('type') == 'dancer':
                roles_data.append(('Leader', leader_data))
                if not dancer_info:
                    dancer_info = leader_data.get('dancer', {})
        
        # Проверяем follower
        if 'follower' in json_data:
            follower_data = json_data['follower']
            if follower_data.get('type') == 'dancer':
                roles_data.append(('Follower', follower_data))
                if not dancer_info:
                    dancer_info = follower_data.get('dancer', {})
        
        # Извлекаем имя
        if dancer_info:
            first_name = dancer_info.get('first_name', '')
            last_name = dancer_info.get('last_name', '')
            result["name"] = f"{first_name} {last_name}".strip()
        
        # Извлекаем поинты для каждой роли
        for role_name, role_data in roles_data:
            placements = role_data.get('placements', {})
            
            # placements структура: {"West Coast Swing": {"NOV": {...}, "INT": {...}, ...}}
            if isinstance(placements, dict):
                for dance_type, divisions in placements.items():
                    if isinstance(divisions, dict):
                        for div_abbr, div_data in divisions.items():
                            if isinstance(div_data, dict) and 'total_points' in div_data:
                                division_name = div_data.get('division', {}).get('name', div_abbr)
                                total_points = div_data.get('total_points', 0)
                                
                                if total_points > 0:
                                    result["divisions"].append({
                                        "division": division_name,
                                        "role": role_name,
                                        "points": int(total_points)
                                    })
        
        # Альтернативная структура: прямой тип "dancer"
        if json_data.get('type') == 'dancer':
            dancer = json_data.get('dancer', {})
            if not result["name"]:
                result["name"] = dancer.get('name') or f"{dancer.get('first_name', '')} {dancer.get('last_name', '')}".strip()
        
        # Альтернативная структура: тип "names"
        elif json_data.get('type') == 'names':
            names = json_data.get('names', [])
            if names and not result["name"]:
                first = names[0]
                result["name"] = first.get('dancer_name', '')
    
    except requests.exceptions.RequestException as e:
        print(f"    Ошибка API запроса: {e}", flush=True)
    except Exception as e:
        print(f"    Ошибка обработки данных: {e}", flush=True)
    
    return result


def get_dancer_points_with_js(wsdc_id: int) -> Dict[str, Any]:
    """
    Получает поинты танцора с рендерингом JavaScript.
    
    Использует Playwright для рендеринга JS в headless режиме.
    
    Args:
        wsdc_id: WSDC ID танцора
    
    Returns:
        Словарь с данными танцора
    """
    try:
        from playwright.sync_api import sync_playwright
        
        result = {
            "wsdc_id": wsdc_id,
            "name": None,
            "divisions": []
        }
        
        url = f"{WSDC_LOOKUP_URL}?q={wsdc_id}"
        
        with sync_playwright() as p:
            # Запускаем браузер в headless режиме
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            
            try:
                # Переходим на страницу
                page.goto(url, timeout=30000)
                
                # Ждём загрузки формы поиска
                page.wait_for_selector('button:has-text("Find Dancer")', timeout=10000)
                
                # Нажимаем кнопку Find Dancer
                page.click('button:has-text("Find Dancer")')
                
                # Ждём загрузки результатов (h1 с именем танцора)
                page.wait_for_selector('h1', timeout=15000)
                
                # Пауза для полной загрузки JS
                page.wait_for_timeout(2000)
                
                # CSS-селекторы для парсинга страницы WSDC
                # ВАЖНО: Если верстка изменится, нужно обновить эти селекторы
                
                # Получаем имя из h1
                h1_elements = page.query_selector_all('h1')
                for h1 in h1_elements:
                    text = h1.inner_text().strip()
                    match = re.match(r'^(.+?)\s*\(\d+\)$', text)
                    if match:
                        result["name"] = match.group(1).strip()
                        break
                
                # Получаем роли и дивизионы
                current_role = None
                
                # Селектор для h2 (роль): "West Coast Swing - Leader"
                h2_elements = page.query_selector_all('h2')
                for h2 in h2_elements:
                    text = h2.inner_text().strip()
                    if ' - ' in text and ('Leader' in text or 'Follower' in text):
                        parts = text.split(' - ')
                        if len(parts) >= 2:
                            current_role = parts[-1].strip()
                            
                            # Ищем h3 после этого h2 (дивизионы с поинтами)
                            # Используем JavaScript для получения следующих элементов
                            next_sibling = h2.evaluate_handle(
                                "el => { let siblings = []; let next = el.nextElementSibling; "
                                "while (next && next.tagName !== 'H2') { siblings.push(next); next = next.nextElementSibling; } "
                                "return siblings; }"
                            )
                            
                            siblings = next_sibling.json_value() if next_sibling else []
                            
                # Альтернативный подход: получаем все h3 с поинтами
                h3_elements = page.query_selector_all('h3')
                for h3 in h3_elements:
                    text = h3.inner_text().strip()
                    # Паттерн: "Novice 24 points" или "All-Stars 31 points"
                    match = re.match(r'^([\w-]+(?:\s+[\w-]+)?)\s+(\d+)\s*points?$', text, re.IGNORECASE)
                    if match:
                        division = match.group(1).strip()
                        points = int(match.group(2))
                        
                        # Определяем роль по предыдущему h2
                        prev_h2 = h3.evaluate("el => { let prev = el.previousElementSibling; "
                                             "while (prev && prev.tagName !== 'H2') prev = prev.previousElementSibling; "
                                             "return prev ? prev.innerText : null; }")
                        
                        role = None
                        if prev_h2 and ' - ' in prev_h2:
                            parts = prev_h2.split(' - ')
                            if len(parts) >= 2:
                                role = parts[-1].strip()
                        
                        if role:
                            result["divisions"].append({
                                "division": division,
                                "role": role,
                                "points": points
                            })
                
            except Exception as e:
                print(f"    Ошибка загрузки страницы: {e}", flush=True)
            finally:
                browser.close()
        
        return result
    
    except ImportError:
        print("  Playwright не установлен, используем базовый парсинг", flush=True)
        return {"wsdc_id": wsdc_id, "name": None, "divisions": []}
    except Exception as e:
        print(f"  Ошибка JS-рендеринга для ID {wsdc_id}: {e}", flush=True)
        return {"wsdc_id": wsdc_id, "name": None, "divisions": []}


def find_best_match(name_en: str, dancers: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    """
    Находит наилучшее совпадение среди найденных танцоров.
    
    Использует более гибкий алгоритм сопоставления, включая:
    - Точное совпадение
    - Совпадение по частям имени
    - Совпадение по началу слов (для обработки вариантов типа "Morgos" vs "Morgosy")
    - Совпадение по фамилии (последнее слово)
    
    Args:
        name_en: Искомое имя на английском
        dancers: Список найденных танцоров
    
    Returns:
        Наилучшее совпадение или None
    """
    if not dancers:
        return None
    
    name_lower = name_en.lower().strip()
    name_parts = name_lower.split()
    name_parts_set = set(name_parts)
    
    # Извлекаем фамилию (последнее слово) и имя (первое слово)
    surname = name_parts[-1] if name_parts else ""
    first_name = name_parts[0] if name_parts else ""
    
    best_match = None
    best_score = 0
    
    for dancer in dancers:
        dancer_name = dancer.get("dancer_name", "").lower().strip()
        dancer_parts = dancer_name.split()
        dancer_parts_set = set(dancer_parts)
        dancer_surname = dancer_parts[-1] if dancer_parts else ""
        dancer_first_name = dancer_parts[0] if dancer_parts else ""
        
        score = 0
        
        # 1. Точное совпадение (максимальный балл)
        if dancer_name == name_lower:
            return dancer
        
        # 2. Совпадение всех частей имени (но в другом порядке)
        if name_parts_set == dancer_parts_set:
            score = 10
        # 3. Совпадение по частям имени
        else:
            common_parts = name_parts_set & dancer_parts_set
            score = len(common_parts) * 2
        
        # 4. Совпадение фамилии (важно!)
        if surname and dancer_surname:
            if surname == dancer_surname:
                score += 5
            elif surname in dancer_surname or dancer_surname in surname:
                # Частичное совпадение фамилии (например, "Morgos" vs "Morgosy")
                score += 3
        
        # 5. Совпадение имени
        if first_name and dancer_first_name:
            if first_name == dancer_first_name:
                score += 3
            elif first_name in dancer_first_name or dancer_first_name in first_name:
                score += 1
        
        # 6. Бонус за совпадение первых букв
        if dancer_name and name_lower:
            if dancer_name[0] == name_lower[0]:
                score += 0.5
        
        if score > best_score:
            best_score = score
            best_match = dancer
    
    # Требуем хотя бы минимальное совпадение (фамилия или имя)
    if best_score >= 1:
        return best_match
    
    return None


def get_dancer_data(name_ru: str, name_en: str, session: requests.Session, 
                    use_js_render: bool = False) -> List[Dict[str, Any]]:
    """
    Получает данные танцора из WSDC.
    
    Пробует разные варианты поиска для повышения вероятности нахождения.
    
    Args:
        name_ru: Имя на русском
        name_en: Имя на английском
        session: requests Session
        use_js_render: Использовать ли JS-рендеринг
    
    Returns:
        Список строк с данными для CSV
    """
    print(f"  Ищу: {name_en}...", flush=True)
    
    # Генерируем варианты поиска
    name_parts = name_en.strip().split()
    search_variants = []
    
    # 1. Полное имя (как есть)
    if len(name_parts) >= 2:
        search_variants.append(name_en)
        # 2. Только фамилия (последнее слово)
        search_variants.append(name_parts[-1])
        # 3. Только имя (первое слово)
        search_variants.append(name_parts[0])
        # 4. Фамилия + первая буква имени
        if len(name_parts[0]) > 0:
            search_variants.append(f"{name_parts[-1]} {name_parts[0][0]}")
    else:
        search_variants.append(name_en)
    
    # Убираем дубликаты, сохраняя порядок
    seen = set()
    unique_variants = []
    for variant in search_variants:
        if variant not in seen:
            seen.add(variant)
            unique_variants.append(variant)
    
    # Пробуем каждый вариант поиска
    all_dancers = []
    for variant in unique_variants:
        if variant != name_en:
            print(f"    Пробую вариант: {variant}...", flush=True)
        dancers = search_wsdc_dancer(variant, session)
        if dancers:
            all_dancers.extend(dancers)
            # Если нашли результаты на первом варианте (полное имя), можно не пробовать остальные
            if variant == name_en and len(all_dancers) > 0:
                print(f"    Найдено на первом варианте, пропускаю остальные", flush=True)
                break
            # Небольшая пауза между вариантами (только если не первый)
            if variant != name_en:
                time.sleep(0.3)
    
    # Убираем дубликаты по wsdc_id
    seen_ids = set()
    unique_dancers = []
    for dancer in all_dancers:
        dancer_id = dancer.get("wsdc_id")
        if dancer_id and dancer_id not in seen_ids:
            seen_ids.add(dancer_id)
            unique_dancers.append(dancer)
    
    if not unique_dancers:
        print(f"    Не найдено совпадений (пробовал варианты: {', '.join(unique_variants)})", flush=True)
        return [{
            "name_ru": name_ru,
            "name_en": name_en,
            "wsdc_id": None,
            "division": "",
            "role": "",
            "points": 0
        }]
    
    # Находим лучшее совпадение
    best_match = find_best_match(name_en, unique_dancers)
    
    if not best_match:
        print(f"    Найдено {len(unique_dancers)} танцоров, но нет точного совпадения", flush=True)
        # Берём первого из списка как запасной вариант
        best_match = unique_dancers[0]
        print(f"    Использую первое совпадение: {best_match.get('dancer_name')}", flush=True)
    
    wsdc_id = best_match.get("wsdc_id")
    found_name = best_match.get("dancer_name", name_en)
    
    print(f"    Найден: {found_name} (ID: {wsdc_id})", flush=True)
    
    # Получаем полные данные о поинтах
    # Сначала пробуем через API (быстрее и надёжнее)
    print(f"    Загружаю поинты через API...", flush=True)
    dancer_data = get_dancer_points_via_api(wsdc_id, session)
    
    # Если API не вернул данные, пробуем Playwright (если доступен)
    if not dancer_data.get("divisions") and use_js_render:
        print(f"    API не вернул данные, пробую Playwright...", flush=True)
        try:
            playwright_data = get_dancer_points_with_js(wsdc_id)
            if playwright_data.get("divisions"):
                dancer_data = playwright_data
                print(f"    Получено дивизионов через Playwright: {len(dancer_data.get('divisions', []))}", flush=True)
        except Exception as e:
            print(f"    Playwright недоступен: {e}", flush=True)
    
    if dancer_data.get("divisions"):
        print(f"    Получено дивизионов: {len(dancer_data.get('divisions', []))}", flush=True)
    
    # Если имя не было получено из HTML, используем имя из поиска
    if not dancer_data.get("name"):
        dancer_data["name"] = found_name
    
    # Формируем результаты
    results = []
    
    if dancer_data.get("divisions"):
        for div in dancer_data["divisions"]:
            results.append({
                "name_ru": name_ru,
                "name_en": dancer_data.get("name", found_name),
                "wsdc_id": wsdc_id,
                "division": div.get("division", ""),
                "role": div.get("role", ""),
                "points": div.get("points", 0)
            })
    else:
        # Если не удалось получить дивизионы, записываем базовую информацию
        print(f"    Не удалось получить детали поинтов", flush=True)
        results.append({
            "name_ru": name_ru,
            "name_en": dancer_data.get("name", found_name),
            "wsdc_id": wsdc_id,
            "division": "",
            "role": "",
            "points": 0
        })
    
    return results


# ==============================================================================
# ЭКСПОРТ ДЛЯ GOOGLE SHEETS
# ==============================================================================

def create_google_sheets_instructions(csv_file: str, df: pd.DataFrame, as_of_date: str):
    """
    Создаёт инструкцию и форматированные данные для вставки в Google Sheets.
    
    Args:
        csv_file: Путь к CSV файлу
        df: DataFrame с данными
        as_of_date: Дата в формате YYYY-MM-DD
    """
    print(flush=True)
    print("=" * 60, flush=True)
    print("📋 ИНСТРУКЦИЯ ДЛЯ ВСТАВКИ В GOOGLE SHEETS", flush=True)
    print("=" * 60, flush=True)
    print(flush=True)
    
    # Создаём HTML файл с инструкцией
    html_file = f"wsdc_points_{as_of_date}_instructions.html"
    
    # Форматируем данные для таблицы в HTML
    html_rows = []
    for idx, row in df.iterrows():
        cells = []
        for col in df.columns:
            value = str(row[col]) if pd.notna(row[col]) else ""
            # Экранируем HTML символы
            value = value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            cells.append(f"<td>{value}</td>")
        html_rows.append(f"<tr>{''.join(cells)}</tr>")
    
    html_content = f"""<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WSDC Points - Инструкция для Google Sheets</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .container {{
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #1a73e8;
            border-bottom: 3px solid #1a73e8;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #34a853;
            margin-top: 30px;
        }}
        .step {{
            background: #f8f9fa;
            padding: 15px;
            margin: 15px 0;
            border-left: 4px solid #1a73e8;
            border-radius: 4px;
        }}
        .step-number {{
            font-weight: bold;
            color: #1a73e8;
            font-size: 1.2em;
        }}
        .data-table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            font-size: 12px;
        }}
        .data-table th {{
            background: #1a73e8;
            color: white;
            padding: 10px;
            text-align: left;
            position: sticky;
            top: 0;
        }}
        .data-table td {{
            padding: 8px;
            border: 1px solid #ddd;
        }}
        .data-table tr:nth-child(even) {{
            background: #f8f9fa;
        }}
        .data-table tr:hover {{
            background: #e8f0fe;
        }}
        .copy-button {{
            background: #34a853;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
            margin: 10px 0;
        }}
        .copy-button:hover {{
            background: #2d8f47;
        }}
        .info-box {{
            background: #e8f0fe;
            border-left: 4px solid #1a73e8;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }}
        .warning-box {{
            background: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }}
        code {{
            background: #f1f3f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }}
        .link {{
            color: #1a73e8;
            text-decoration: none;
        }}
        .link:hover {{
            text-decoration: underline;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 WSDC Points - Инструкция для вставки в Google Sheets</h1>
        
        <div class="info-box">
            <strong>📅 Дата данных:</strong> {as_of_date}<br>
            <strong>📝 Всего записей:</strong> {len(df)}<br>
            <strong>📁 CSV файл:</strong> <code>{csv_file}</code>
        </div>
        
        <h2>📋 Способ 1: Импорт CSV файла (Рекомендуется)</h2>
        
        <div class="step">
            <span class="step-number">Шаг 1:</span> Откройте Google Sheets по ссылке:<br>
            <a href="https://docs.google.com/spreadsheets/d/{GOOGLE_SHEET_ID}/edit" target="_blank" class="link">
                https://docs.google.com/spreadsheets/d/{GOOGLE_SHEET_ID}/edit
            </a>
        </div>
        
        <div class="step">
            <span class="step-number">Шаг 2:</span> Создайте новый лист (или выберите существующий) для данных WSDC Points
        </div>
        
        <div class="step">
            <span class="step-number">Шаг 3:</span> В меню выберите <strong>Файл → Импортировать</strong>
        </div>
        
        <div class="step">
            <span class="step-number">Шаг 4:</span> Выберите вкладку <strong>"Загрузить"</strong> и загрузите файл <code>{csv_file}</code>
        </div>
        
        <div class="step">
            <span class="step-number">Шаг 5:</span> В настройках импорта выберите:
            <ul>
                <li><strong>Разделитель:</strong> Запятая</li>
                <li><strong>Преобразовать текст в числа, даты и формулы:</strong> Да</li>
            </ul>
        </div>
        
        <h2>📋 Способ 2: Копирование через буфер обмена</h2>
        
        <div class="step">
            <span class="step-number">Шаг 1:</span> Откройте файл <code>{csv_file}</code> в Excel, Notepad++ или другом редакторе
        </div>
        
        <div class="step">
            <span class="step-number">Шаг 2:</span> Выделите все данные (Ctrl+A) и скопируйте (Ctrl+C)
        </div>
        
        <div class="step">
            <span class="step-number">Шаг 3:</span> Откройте Google Sheets и вставьте данные (Ctrl+V) в нужную ячейку
        </div>
        
        <div class="warning-box">
            <strong>⚠️ Важно:</strong> При копировании через буфер обмена убедитесь, что кодировка UTF-8 сохранена, 
            иначе русские имена могут отображаться некорректно.
        </div>
        
        <h2>📊 Предварительный просмотр данных</h2>
        
        <p>Ниже показаны первые 100 строк данных. Для просмотра всех данных используйте CSV файл.</p>
        
        <table class="data-table">
            <thead>
                <tr>
                    {' '.join([f'<th>{col}</th>' for col in df.columns])}
                </tr>
            </thead>
            <tbody>
                {''.join(html_rows[:100])}
            </tbody>
        </table>
        
        {f'<p><em>Показано 100 из {len(df)} записей. Откройте CSV файл для просмотра всех данных.</em></p>' if len(df) > 100 else ''}
        
        <div class="info-box">
            <strong>💡 Совет:</strong> После импорта данных вы можете:
            <ul>
                <li>Отформатировать заголовки (жирный шрифт, цвет фона)</li>
                <li>Добавить фильтры (Данные → Создать фильтр)</li>
                <li>Создать сводные таблицы для анализа</li>
                <li>Добавить условное форматирование для визуализации поинтов</li>
            </ul>
        </div>
        
        <hr style="margin: 30px 0; border: none; border-top: 2px solid #ddd;">
        
        <p style="text-align: center; color: #666;">
            Сгенерировано автоматически скриптом <code>wsdc_from_google_sheet.py</code><br>
            Дата: {time.strftime('%Y-%m-%d %H:%M:%S')}
        </p>
    </div>
</body>
</html>"""
    
    # Сохраняем HTML файл
    with open(html_file, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"✅ Создан файл с инструкцией: {html_file}", flush=True)
    print(flush=True)
    print("📌 КРАТКАЯ ИНСТРУКЦИЯ:", flush=True)
    print(f"   1. Откройте Google Sheets: https://docs.google.com/spreadsheets/d/{GOOGLE_SHEET_ID}/edit", flush=True)
    print(f"   2. Создайте новый лист для данных WSDC Points", flush=True)
    print(f"   3. Файл → Импортировать → Загрузить → выберите '{csv_file}'", flush=True)
    print(f"   4. Или откройте '{html_file}' в браузере для подробной инструкции", flush=True)
    print(flush=True)


# ==============================================================================
# ОСНОВНАЯ ФУНКЦИЯ
# ==============================================================================

def main(as_of_date: str):
    """
    Основная функция скрипта.
    
    Args:
        as_of_date: Дата в формате YYYY-MM-DD
    """
    print("=" * 60, flush=True)
    print("WSDC Points Collector", flush=True)
    print(f"Дата: {as_of_date}", flush=True)
    print("=" * 60, flush=True)
    
    # 1. Загружаем данные из Google Sheets
    try:
        df = read_google_sheet(GOOGLE_SHEET_ID)
    except Exception as e:
        print(f"Ошибка загрузки Google Sheets: {e}", flush=True)
        sys.exit(1)
    
    # Проверяем наличие столбца "Имя"
    # Возможные названия столбца с именами
    name_column = None
    for col in ['Имя', 'имя', 'Name', 'name', 'ФИО', 'фио']:
        if col in df.columns:
            name_column = col
            break
    
    if name_column is None:
        print(f"Ошибка: не найден столбец с именами. Доступные столбцы: {list(df.columns)}", flush=True)
        sys.exit(1)
    
    print(f"Столбец с именами: '{name_column}'", flush=True)
    print(f"Найдено {len(df)} записей", flush=True)
    print(flush=True)
    
    # 2. Создаём сессию для запросов
    session = requests.Session()
    # В средах с заданным HTTP(S)_PROXY requests может пытаться ходить через прокси.
    # Для стабильной работы (и чтобы не упираться в недоступный прокси) отключаем trust_env.
    session.trust_env = False
    
    # 3. Собираем данные для каждого танцора
    all_results = []
    
    # Проверяем, установлен ли Playwright для JS-рендеринга
    try:
        from playwright.sync_api import sync_playwright
        use_js_render = True
        print("Playwright найден, будет использоваться JS-рендеринг", flush=True)
    except ImportError:
        use_js_render = False
        print("Playwright не установлен, используется базовый парсинг", flush=True)
        print("Для получения детальных поинтов установите:", flush=True)
        print("  pip install playwright && python -m playwright install chromium", flush=True)
    
    print(flush=True)
    
    for idx, row in df.iterrows():
        name_ru = str(row[name_column]).strip()
        
        if not name_ru or name_ru == 'nan':
            continue
        
        # Транслитерируем имя
        name_en = ru_to_en(name_ru)
        
        print(f"[{idx + 1}/{len(df)}] {name_ru} -> {name_en}", flush=True)
        
        # Получаем данные из WSDC
        results = get_dancer_data(name_ru, name_en, session, use_js_render)
        
        # Добавляем дату
        for r in results:
            r["as_of_date"] = as_of_date
        
        all_results.extend(results)
        
        # Пауза между запросами
        import random
        delay = random.uniform(REQUEST_DELAY_MIN, REQUEST_DELAY_MAX)
        time.sleep(delay)
    
    # 4. Сохраняем результаты
    if all_results:
        output_df = pd.DataFrame(all_results)
        
        # Упорядочиваем столбцы
        columns_order = ['name_ru', 'name_en', 'wsdc_id', 'division', 'role', 'points', 'as_of_date']
        output_df = output_df[[c for c in columns_order if c in output_df.columns]]
        
        output_file = f"wsdc_points_{as_of_date}.csv"
        output_df.to_csv(output_file, index=False, encoding='utf-8')
        
        print(flush=True)
        print("=" * 60, flush=True)
        print(f"Готово! Результаты сохранены в: {output_file}", flush=True)
        print(f"Всего записей: {len(output_df)}", flush=True)
        print("=" * 60, flush=True)
        
        # 5. Создаём инструкцию для вставки в Google Sheets
        create_google_sheets_instructions(output_file, output_df, as_of_date)
    else:
        print("Нет данных для сохранения", flush=True)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Использование: python wsdc_from_google_sheet.py YYYY-MM-DD", flush=True)
        print("Пример: python wsdc_from_google_sheet.py 2026-01-28", flush=True)
        sys.exit(1)
    
    as_of_date = sys.argv[1]
    
    # Проверяем формат даты
    import re
    if not re.match(r'^\d{4}-\d{2}-\d{2}$', as_of_date):
        print(f"Ошибка: дата должна быть в формате YYYY-MM-DD, получено: {as_of_date}", flush=True)
        sys.exit(1)
    
    main(as_of_date)
